### PR TITLE
Feature/disable web security

### PR DESCRIPTION
**Pull request by wiederkehr**
As discussed in the issue #99, I've added a command line option to disable web security allowing content to be loaded via HTTP even if the target URL is HTTPS.

### CODE REVIEW

**Comment by jiahaog** [comment]
Thanks! Is there a website serving insecure content that I can test this on?

**Comment by jiahaog** [comment]
Also, could you merge in changes from development into your branch so that I can merge this PR automatically?

**Comment by jiahaog** [comment]
Actually I'll just merge and fix the conflicts for you since I have the time now!

**Comment by jiahaog** [comment]
Thank you so much!!

**Comment by wiederkehr** [comment]
Thanks for taking care of merging the branches and sorry for the late reply (time zones). Great that this worked out!

**Comment by jiahaog** [comment]
You're welcome! Thank you for your contribution as well!

**Pull request merged**
