### PR TITLE
added user agent parmeter

### PR DESCRIPTION
**Pull request by rispig**
use --ua=\<user agent string\>

### CODE REVIEW

**Comment by jiahaog** [comment]
Sorry for the delay, I've been really busy with school and didn't have time until now. I've changed the implementation of how the app is packaged and added in your changes in 48345eceb5260b62ee1bda1f5c21f586fdfe29b9, but there seems to be some issue with how the user agent is changed. 

When I change the user agent and visit sites like http://whatsmyuseragent.com/, the change does not appear to take effect. However, when I run `navigator.userAgent` in the developer console, it returns the correct modified user agent. Did you get this problem on your side when you implemented the fix, or is this a bug with the later version (v0.36.4) of electron?

**Comment by rispig** [comment]
Same.
Guess it's an issue with electron :(

**Comment by jiahaog** [comment]
I realised that it's not an issue with electron. Setting the user agent in 
```javascript
mainWindow.loadUrl('...', {userAgent: USER_AGENT});
```
sets the user agent for the entire window that appears, and hence when we enter `navigator.userAgent`, in the developer tools (which is in the context of the main window), we receive a valid `navigator.userAgent`. However, what we want is to set the user agent of the `webview` container which shows the target url, and this can be done by doing the following in `index.js`

```javascript
webView.addEventListener('did-start-loading', function() {
    webView.setUserAgent(appArgs.userAgent);
});
```

**Comment by rispig** [comment]
Oh! Nice catch!  
  

Cheers,

Omri.

> On Jan 19 2016, at 12:10 pm, Jia Hao &lt;notifications@github.com&gt; wrote:  

>

> I realised that it's not an issue with electron. Setting the user agent in

>  
>  
>     mainWindow.loadUrl('...', {userAgent: USER_AGENT});

>

> sets the user agent for the entire window that appears, and hence when we
enter navigator.userAgent, in the developer tools (which is in the context of
the main window), we receive a valid navigator.userAgent. However, what we
want is to set the user agent of the webview container which shows the target
url, and this can be done by doing the following in index.js

>  
>  
>     webView.addEventListener('did-start-loading', function() {

>         webView.setUserAgent(appArgs.userAgent);

>     });

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/jiahaog
/nativefier/pull/8#issuecomment-172803605).

**Pull request closed without merging**
