### PR TITLE
Fix #461 & address #375 in Docker: move Dockerfile to Debian and use wine32

### LINKED ISSUE #461: Docker build fails on failing to parse mime-db/db.json
### Description

The `docker build` command fails and doesn't produce anything.

### Steps to reproduce issue

Checkout the project @ tag `v7.4.1` and issue the `docker build -t local/nativefier .` command.
Tried also with `v7.4.0` but still nothing.

### Details

- Version of Docker `17.09.0-ce, build afdb6d4`
- Version of Nativefier (run `nativefier --version`): `v7.4.1` (checked out the corresponding tag)
- Version of node.js (run `node --version`): `v7.10.1`
- OS: `Linux 4.10.0-35-generic`
- Error message / stack trace (if any):
```
[...]
> nativefier@7.4.1 build /nativefier
> gulp build

[13:51:25] Requiring external module babel-register
[13:51:26] Using gulpfile /nativefier/gulpfile.babel.js
[13:51:26] Starting 'build'...
[13:51:26] Starting 'clean'...
[13:51:26] Finished 'clean' after 8.06 ms
[13:51:26] Starting 'build-cli'...
[13:51:26] Starting 'build-static-js'...
[13:51:26] Starting 'build-static-not-js'...
[13:51:26] Starting 'build-tests'...
[13:51:26] Finished 'build-static-not-js' after 383 ms
[13:51:26] Finished 'build-static-js' after 442 ms
[13:51:26] Starting 'build-static'...
[13:51:26] Finished 'build-static' after 67 μs
[13:51:26] Starting 'build-app'...
[13:51:27] Finished 'build-tests' after 1.05 s

internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^
Error: ./app/~/mime-db/db.json
Module parse failed: /nativefier/app/node_modules/mime-db/db.json Unexpected token (2:40)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:40)
    at Parser.pp$4.raise (/nativefier/node_modules/webpack/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/nativefier/node_modules/webpack/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp.semicolon (/nativefier/node_modules/webpack/node_modules/acorn/dist/acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (/nativefier/node_modules/webpack/node_modules/acorn/dist/acorn.js:966:10)
    at Parser.pp$1.parseStatement (/nativefier/node_modules/webpack/node_modules/acorn/dist/acorn.js:730:24)
    at Parser.pp$1.parseBlock (/nativefier/node_modules/webpack/node_modules/acorn/dist/acorn.js:981:25)
    at Parser.pp$1.parseStatement (/nativefier/node_modules/webpack/node_modules/acorn/dist/acorn.js:709:33)
    at Parser.pp$1.parseTopLevel (/nativefier/node_modules/webpack/node_modules/acorn/dist/acorn.js:638:25)
    at Parser.parse (/nativefier/node_modules/webpack/node_modules/acorn/dist/acorn.js:516:17)
    at Object.parse (/nativefier/node_modules/webpack/node_modules/acorn/dist/acorn.js:3098:39)
 @ ./app/~/mime-db/index.js 11:17-37

npm info lifecycle nativefier@7.4.1~build: Failed to exec build script
npm ERR! Linux 4.10.0-35-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v7.10.1
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nativefier@7.4.1 build: `gulp build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nativefier@7.4.1 build script 'gulp build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nativefier package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nativefier
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nativefier
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/.npm/_logs/2017-10-09T13_51_27_980Z-debug.log
The command '/bin/sh -c cd /nativefier/app && npm install     && cd /nativefier && npm install && npm run build && npm install -g     && rm -rf /nativefier' returned a non-zero code: 1
```

### PR DESCRIPTION
**Pull request by ronjouch**
Feedback welcome @toschneck @filippobuletto

- Should address #375 (building a win app from linux) under Docker, thanks @dipenpatel235 for the suggestion to use `wine32` at #375 (comment)
- Regarding #461, [Docker build](https://hub.docker.com/r/jiahaog/nativefier/builds/) seems fine but it was already fine for some time, not sure what happened.

Also clean up a bit the Dockerfile using suggestions from Dockerfile linter [hadolint](https://github.com/lukasmartinelli/hadolint/).

### CODE REVIEW

**Comment by toschneck** [comment]
I just made a small review, and I think all look fine. Currently I didn't test it for windows, but under Linux all looks perfect. I just wondering why you go back to debian, on my PR @JaKXz wanted to have alpine as base image :confused:  https://github.com/jiahaog/nativefier/pull/311/files/34a5ff8be315ae27e86a15f673d13e3359023901

I general I think debian will be the better base image because alpine are not focusing UI packages. Maybe also help @benjaminbarbe https://github.com/jiahaog/nativefier/pull/311#issuecomment-329412205

**Comment by ronjouch** [comment]
> *"I just wondering why you go back to debian, on my PR @JaKXz wanted to have alpine as base image 😕"*

@toschneck the reason is documented at (currently) line 6: I tried staying with Alpine (which I like too), but it doesn't let me fix the wine32 bug. As far I I know, Alpine doesn't have multiarch, preventing us from fixing #375 by installing a 32bit Wine package under a 64bit OS. So I went with Debian, which supports this.

**Comment by toschneck** [comment]
@ronjouch ok good to know. Let's go for it :wink:

**Comment by JaKXz** [comment]
:+1: thanks for the explanation

**Pull request merged**
