### PR TITLE
flash support #2

### PR DESCRIPTION
**Pull request by brunoqueiros**

### CODE REVIEW

**Comment by jiahaog** [comment]
Hi there, if I'm not wrong you linked the parent directory of the app for the flash plugin, with this line:

```
app.commandLine.appendSwitch('ppapi-flash-path', path.join(__dirname, '../plugins', 'libpepflashplayer.so'));
```

I haven't actually got around to testing it, but shouldn't the directory reference the exact path to the plugin within the chrome app on the user's computer?

**Comment by brunoqueiros** [comment]
If the user doesn't have the chrome installed he'll not have the plugin and if the plugin is in a parent directory the user always will have.

I made some tests on Linux (Ubuntu, Linux Mint) and Windows 10.

**Comment by jiahaog** [comment]
Sorry for the late reply, I've done a test on OSX on https://helpx.adobe.com/flash-player.html and it does not appear to work. Perhaps you have to reference the chrome pepper flash path directly?

This is what it says for me in my `chrome://plugins` for Flash

```
Adobe Flash Player - Version: 20.0.0.286
Shockwave Flash 20.0 r0
Name:	Shockwave Flash
Description:	Shockwave Flash 20.0 r0
Version:	20.0.0.286
Location:	/Applications/Google Chrome.app/Contents/Versions/48.0.2564.97/Google Chrome Framework.framework/Internet Plug-Ins/PepperFlash/PepperFlashPlayer.plugin
Type:	PPAPI (out-of-process)
 	Disable
MIME types:	
MIME type	Description	File extensions
application/x-shockwave-flash	Shockwave Flash	
.swf
application/futuresplash	FutureSplash Player	
.spl

```

**Comment by MakuSensei** [comment]
it might in some future version of nativefier
add the command line the ability to copy the flash plugin to main directory resources / lib / "pepflashplayer.dll"

for websites that need flash can be used as Spotify web

with the possibility that this enabled to operate

**Comment by jiahaog** [comment]
Would it be possible to add a script to automatically find the path of the flash plugin from chrome for the user, so that he does not have to specify it directly?

**Comment by MakuSensei** [comment]
of fine by me that automatically use the plugin directory google chrome. OwO

the problem is those who do not use google chrome will be obliged to install

disculpa mi ingles, use google traductor :p

**Pull request merged**
