### PR TITLE
Upgrade dependencies and default to latest Electron 1.7.9

### PR DESCRIPTION
**Pull request by ronjouch**
@jiahaog This is the irregularly-scheduled mass deps upgrade to Nativefier. Electron 1.7.9 seems okay, I see it's used by big Electron apps like Itch. Apart from that, nothing groundbreaking looking at individual deps changelogs but, as usual, potential hiccups are probable. Also,

- Slip in a few minor development/documentation nits and fix new eslint errors
- Stop using `package-lock.json`s and disable their automatic generation with npm5. In theory they're great, in practice they complicate PRs. Also, I accidentally let [a PR](https://github.com/jiahaog/nativefier/pull/419) remove the main lockfile without any breakage and anyone noticing, which may be a sign semver compatibility conventions are honored these days and we can roll along fine with a simple `package.json`. I suspect I'll revert this after hitting a couple of unannounced breaking changes in a minor update, but I'd like to try it anyway 🙂.

@jiahaog feedback and tests welcome (I've been using it for a few days, all good with my -limited- use cases), then when you're okay with it, go ahead and merge but **please don't release immediately**, I'll first ask for more regression testing from contributors.

### CODE REVIEW

**Comment by ronjouch** [comment]
As discussed above, pinging a few Nativefier contributors having shown interest in the past with issue reports or pull requests.

Hello everybody and sorry for the noise 🙂. This PR I just merged as 6fb3b92 updates all Nativefier deps, including Electron. If you still use Nativefier and have a few spare cycles to contribute, could you [build `master`](https://github.com/jiahaog/nativefier/blob/master/docs/development.md), re-package your apps, and report regressions here? Thanks!

@desimaniac @GitGeoCoder @princejosuah @cbess @brianblakely @omouren @mdh34 @githubbob42 @xldrx @onedr0p @usrbowe @david-pacheco @romo-dw @skoshy @darrenhaken @toschneck @zbicin. Of course, do tell me if you no longer have interest/time in nativefier and don't want to hear from me again.

**Comment by mdh34** [comment]
@ronjouch no regressions to report :)

**Comment by desimaniac** [comment]
@ronjouch Pulled/built master, tested app packaging. Everything looks good!

**Comment by zbicin** [comment]
@ronjouch unfortunately I don't have much free time right now. You don't have to notify me in the near future ;)

**Comment by cbess** [comment]
@ronjouch Tested out `v7.5.1`, everything looks good to me.

**Comment by githubbob42** [comment]
@ronjouch<https://github.com/ronjouch> Sorry for the delay - all looks good.  Thanks for updating this!

Bob Roth
LiquidFrameworks
24 E Greenway Plaza, Suite 405
Houston, TX 77046
(713) 552-9250 (main)
(713) 552-9251 (fax)
http://www.liquidframeworks.com<http://www.liquidframeworks.com/>
broth@liquidframeworks.com<mailto:broth@liquidframeworks.com>

**Pull request merged**
