### PR TITLE
make keeping os x apps running optional

### PR DESCRIPTION
**Pull request by matthewdias**
this implements #174

### CODE REVIEW

**Comment by jiahaog** [comment]
Is this really necessary? The default behaviour for OSX apps is to simply hide the window and not quit the app when the window is closed, and I'm inclined to keep the same behaviour

**Comment by matthewdias** [comment]
@jiahaog its also very common for OSX apps to quit after you've closed the last window. It's up to the discretion of the developer. In my experience, the apps that do have this behavior, are ones that don't expect to be used over a long period of time. For example, your to do list might stay running since you access it many times throughout the day, however, photo and video editors help you achieve one task, and then aren't useful anymore until you happen to need them again. I think webapps in particular would benefit from this functionality, because many of them are things you would bring up to do something, and then would quit them when you're done. Doing it automatically on window close just makes it easier, and in the end, its up to the user if they want to use it.

**Comment by matthewdias** [comment]
would it make more sense if the default was true instead of false? I don't really mind if you think this shouldn't be merged at all. it's just a feature I wanted for myself.

**Comment by jiahaog** [comment]
Sorry, I'm just a little busy with school and all. Yup, I wouldn't mind the flag but I would rather it hide the app by default. On a side note, do you think it would be better to have this as a menu bar option instead of a command line flag?

**Comment by matthewdias** [comment]
Alright I can reverse the behavior when I get time. Busy with school too xD. I don't think its really necessary as a menu bar option, as you'd probably want the same functionality every time for a given app (At least I would). That made me think, though, it might be cool to have a preferences pane where you could change the values that you initially set using the command.

**Comment by priezz** [comment]
I agree with @matthewdias, that the option is much more useful in the command line.

**Comment by priezz** [comment]
As for the menu I prefer to get rid of the Nativefier items in the menu and replace them with the running app's items.

**Comment by matthewdias** [comment]
I updated with the changes on `development` and reversed the default behavior.

**Comment by deksden** [comment]
For small utility apps on OSX its common to make app close on window close. Its per-app setting, so command line switch will be ok

**Comment by jiahaog** [comment]
Thank you, it works great!

**Pull request merged**
