### PR TITLE
FIX #590: Ensure secondary windows have the same behaviors as the mainWindow

### LINKED ISSUE #590: New windows are not configured properly
### Description

When opening a secondary window using the "Open Link in New Window" context menu item, the created window is not configured properly.  JavaScript does not work, and this error appears in the console:

```
Electron Security Warning This renderer process has Node.js integration enabled and attempted to load remote content. This exposes users of this app to severe security risks.
For more information and help, consult https://electronjs.org/docs/tutorial/security
(anonymous) @ /Applications/Puppet Tickets.app/Contents/Resources/electron.asar/renderer/init.js:162
```

### Steps to reproduce issue

Wrap `tickets.puppet.com`. Try to open a link to a ticket in a new window.  Notice that the content looks garbled and that the JavaScript console contains lots of errors.

### Details

This problem occurs because the new window is created like this:

    new BrowserWindow()

No options are specified; among others, these critically are missing:

    webPreferences: {
      javascript: true,
      nodeIntegration: false,
    }

### PR DESCRIPTION
**Pull request by bacongravy**
As described in #590, new windows are not being configured properly. This change refactors window creation so that a common base set of window behaviors can be shared between the mainWindow and new windows that are created.

### CODE REVIEW

**Comment by bacongravy** [comment]
Node 4 and node 5 are failing with:

    The command "npm run dev-up" failed and exited

It looks like maybe the version of npm being used isn't compatible with the version of node?

**Comment by ronjouch** [comment]
@bacongravy 

- Children window no longer close on closing parent window, that fixes https://github.com/jiahaog/nativefier/issues/439 . Awesome 🙂.
- I got a crash opening a GoogleCal window from Gmail. Never had one before. Have you ever had crashes?
- I checked how Gmail's *"Open in new window"* feature works with this. Like before ( https://github.com/jiahaog/nativefier/issues/408 ), it opens a blank window, but in addition to that it opens a dialog saying *"Grrr! A popup blocker may be preventing the application from opening the page. If you have a popup blocker, try disabling it to open the window"*. Ideas?
- Regarding Travis builds failing, yeah it's freshly-out-of-the-oven npm@6.0.0 having [dropped support for Node 4 and 7](https://github.com/npm/npm/releases/tag/v6.0.0-next.0): *"BREAKING SUPPORTED NODE VERSIONS: Per our supported Node.js policy, we're dropping support for both Node 4 and Node 7, which are no longer supported by the Node.js project"*. I [tamed travis to stay on 5.8](https://github.com/jiahaog/nativefier/commit/eeef1facf37ee9d512c46fd72312a9aa0fd7f231), your next builds should pass!

**Comment by bacongravy** [comment]
* (fixes 439) 👍
* I have not seen crashes from secondary windows (but I've only tested on macOS). Do you have steps to reproduce?
* I have seen the "Grrr!" message in my nativefier-built Gmail app for as long as I've been using it (>1 year) so I don't attribute that behavior to these changes.
* (tamed travis) 👍

**Comment by ronjouch** [comment]
> *"I have not seen crashes from secondary windows (but I've only tested on macOS). Do you have steps to reproduce?"*

@bacongravy Clicking on the "More details" link of the Google Calendar sidebar gadget for Gmail. But ignore that, I only saw it once. Was just checking with you if that rang a bell.

gmail-more-details

**Comment by ronjouch** [comment]
Merged! One more :+1: , @bacongravy 🙂

**Pull request merged**
