### PR TITLE
feat(global-shortcus): allow global shortcuts that trigger input events

### LINKED ISSUE #15: Feature Request: Global keyboard shortcuts
Would it be possible to create a config (or JavaScript) file to bind some keypresses to JavaScript console injections?

For example, music players could bind the media keys to JavaScript commands to start, stop and skip.

### PR DESCRIPTION
**Pull request by axe312ger**
This adds a new configuration feature which allows the user to define global shortcuts which trigger input events within the main window.

That way, I could easily wrap SoundCloud and Deezer to create a native app which reacts on my keyboard media buttons.

fixes #15

Ps.: My vscode updated the TOC of the api.md, I guess it is fine to commit it with this :)

### CODE REVIEW

**Comment by axe312ger** [comment]
Just found out my example shortcuts should work for SoundCloud.com as well 🙈 😍

**Comment by ronjouch** [comment]
@axe312ger tested, working, thanks 🙂. I would like more docs before I merge:

1. Please document the syntax expected by Electron to bind combinations? Say a user wants to bind <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>Alt</kbd> + <kbd>P</kbd>, what `"key"` should they pass in their json?
2. Please document the name of special keys for Ctrl / Cmd / CtrlOrCmd / would Ctrl work under macOS? Links to electron docs welcome.
3. Please link to electron docs listing the special keycodes (is page up `pgup` or `pageup` or whatever?)
4. Please link to electron docs listing the available `type`s (other than `keyDown`).
5. More generally, link to any relevant electron docs 😄.

**Comment by axe312ger** [comment]
Hey @ronjouch,

I guess I included already the links you are asking for, but I extended the docs further to have more details about how to actually use this. Please have a look if it now fits your expectations :)

All the best,
Benedikt

**Comment by ronjouch** [comment]
@axe312ger fantasbulous, thanks! Extra :100: :100: :100: for the doc details, it seems not much but it's super important to make the difference between "uh no word on how to use this thing, damned I'll have to look at the code" and "oh neat, examples!"

Merging. Will cut a new release soon.

**Pull request merged**
