### PR TITLE
Release 7.4.1

### PR DESCRIPTION
**Pull request by ronjouch**
A few users asked for a release bundling recent fixes, let's do that.

@jiahaog letting you create the tag/release too, or I can do it once this is merged.

### CODE REVIEW

**Comment by jiahaog** [comment]
@ronjouch Thanks a lot!

**Comment by aharpervc** [comment]
Will this also be pushed to npm soon?

**Comment by ronjouch** [comment]
> *Will 7.4.1 be pushed to npm soon?*

@jiahaog ? But wait, if it's not done, please don't do it before doing a smoketest. I just tried building it and it seems to fail. Not sure if it's due to something I merged, or a broken dep, and I won't be able to check before next Monday. Keep me posted.

**Comment by jiahaog** [comment]
Ah, seems like the CI build on travis has failed. Let me look into it

**Comment by jiahaog** [comment]
I've manually published 7.4.1 to npm. It seems to be a dependency issue, I've fixed it using npm pacakge-lock.json in 33fe71a85557a8be204e7d2b3867793c5719fc77

**Comment by ronjouch** [comment]
> *"I've manually published 7.4.1 to npm. It seems to be a dependency issue, I've fixed it using npm pacakge-lock.json in 33fe71a"*

Thanks @jiahaog 👍.

**Pull request merged**
