### PR TITLE
Support architecture arm64 (fix #804)

### LINKED ISSUE #804: Add support for architecture arm64
### Description

Thanks for the cool project and your work. I like it very much and use it for Whatsapp Web.

I tried running it on my ChromeBook with an arm64-CPU within crostini linux VM and it worked, but just after I added the architecture "arm64" to the check in file nativefier/src/infer/inferOs.js.

### Steps to reproduce issue

1.) Installing the build environment and nativefier
sudo apt-get install curl software-properties-common
sudo apt-get install libnss3-dev
curl -sL https://deb.nodesource.com/setup_11.x | sudo bash -
sudo apt-get install nodejs
git clone https://github.com/jiahaog/nativefier
cd nativefier
sudo npm install nativefier -g

2.) create App for WhatsApp Web
nativefier web.whatsapp.com

Stops with error, see Details below.

I added in file nativefier/src/infer/inferOs.js the function inferArch() the architecture "arm64" and it "worked".
`  if (arch !== 'ia32' && arch !== 'x64' && arch !== 'arm64' && arch !=='arm') {
  //if (arch !== 'ia32' && arch !== 'x64' && arch !=='arm') {`

Well actually only changing nativefier/src/infer/inferOs.js was not enouth. Even after a "uninstall" and a new "install" the installed file /usr/lib/node_modules/nativefier/lib/infer/infer/inferOs.js was still not changed? I have no idea if this file is cached somewhere or if the install downloads interOs.js fresh from Web during install?
Anyway after I changed also /usr/lib/node_modules/nativefier/lib/infer/infer/inferOs.js and add there "arm64" too it realy worked without any problem and generates an App for Linux that runs fine on my system.

### Details

My system is a ASUS Chromebook Flip C101PA running with ChromeOs 74.0.3729.125.
I used nativefier within the linux VM called "crostini" of ChromeOS.

Here the error message saying that "arm64" is not supported:
` inferring [                                                  ] 0%
/usr/lib/node_modules/nativefier/lib/infer/infer/inferOs.js:20
    throw new Error(`Incompatible architecture ${arch} detected`);
          ^
Error: Incompatible architecture arm64 detected
    at inferArch (/usr/lib/node_modules/nativefier/lib/infer/infer/inferOs.js:20:11)
    at exports.default (/usr/lib/node_modules/nativefier/lib/options/options/optionsMain.js:23:30)
    at /usr/lib/node_modules/nativefier/lib/build/build/buildMain.js:175:9
    at nextTask (/usr/lib/node_modules/nativefier/node_modules/async/dist/async.js:5324:14)
    at Object.waterfall (/usr/lib/node_modules/nativefier/node_modules/async/dist/async.js:5334:5)
    at buildMain (/usr/lib/node_modules/nativefier/lib/build/build/buildMain.js:171:9)
    at Object.<anonymous> (/usr/lib/node_modules/nativefier/lib/cli.js:248:16)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
    at internal/main/run_main_module.js:21:11`

### PR DESCRIPTION
**Pull request by cassidyjames**
I believe this should fix #804 based on comments there, but I need to figure out how to test it.

### CODE REVIEW

**Comment by ronjouch** [comment]
> I believe this should fix #804 based on comments there, but I need to figure out how to test it.

@cassidyjames yeah I suspect it's enough, but I don't have hardware to test it. Happy to merge what you have once you confirm you were able to test it. Thanks!

**Comment by cassidyjames** [comment]
Tested locally on a Pinebook Pro running elementary OS, and it works!

**Comment by ronjouch** [comment]
> Tested locally on a Pinebook Pro running elementary OS, and it works!

:tada: ! Can you grep a bit around and look for potential docs (and maybe code) to update?

**Comment by damiankorcz** [comment]
Tested on Raspberry Pi 4 Model B running Manjaro ARM (aarch64). Built an app no problem and seems all functional. Used Notion to test.

**Comment by ronjouch** [comment]
> Tested on Raspberry Pi 4 Model B running Manjaro ARM (aarch64). Built an app no problem and seems all functional. Used Notion to test.

@damiankorcz great, thanks for the test! Merged and released as Nativefier 10.1.0

**Pull request merged**
