### PR TITLE
Fixes #435 - Apps using DRM via Widevine

### LINKED ISSUE #435: [Feature] Add WidevineCdm plugin
### Description

I think it would be a great idea to add the WidevineCDM plugin into the app, because it can block certain website like Amazon Prime Video for example

See that link : https://github.com/electron/electron/blob/master/docs/tutorial/using-widevine-cdm-plugin.md 

### Steps to reproduce issue
-> Go on Amazon Prime Video and Log In
-> Try to play a video

### Details

- Are you nativefying a *public* website?
--> Yes, https://www.primevideo.com/
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs?
--> Nothing seems to deal with that in help
- Full nativefier command used to build your app: `nativefier --name "Prime Video" "https://www.primevideo.com/"`
- Version of Nativefier (run `nativefier --version`): `v7.4.1`
- Version of node.js (run `node --version`): `v6.11.1`
- OS: `Windows 10 Enterprise`

### PR DESCRIPTION
**Pull request by brianblakely**
The plugin is stored in appdata, so the user should only ever need to download it once for all nativefier apps they create.

### CODE REVIEW

**Comment by ronjouch** [comment]
@brianblakely over at https://github.com/jiahaog/nativefier/issues/68#issuecomment-328440151 , @xdgc notes that this PR didn't work for them, but offers a few proposals. Could the two of you discuss what didn't work for @xdgc and maybe improve this PR? Thanks 🙂.

**Comment by xdgc** [comment]
I'm not sure how to determine what failed. If I understand the PR it's trying to download the plugin in runtime, which sounds wise, but I can't see that it's happening. And I don't know enough about electron to find why.

**Comment by jiahaog** [comment]
I've just glanced through the source code for https://github.com/webcatalog/electron-widevinecdm briefly. I could be wrong, but it seems like it is downloading a prepackaged widevine binary and we are dependent on the upstream for versioning. Would it be easier to instead assume that the user has Chrome installed, and hence read from that directory?

Something like https://github.com/jiahaog/nativefier/commit/6ca4e794cdbc5b4884cd2c05b9a56f1c4e139cd1 (for flash but the same idea)? Sorry if I'm a little out of touch with things, feel free to correct me if it should/should not work 😄

**Comment by xdgc** [comment]
I think relying on upstream for version is exactly what's attractive. There can be a substantial gap between the Chrome runtime version used by Electron and that in the user's local Chrome installation (if any). If the widevine plugin is not compatible (as between nativefier's Chrome 56 and my Chrome 61) then the plugin just appears unavailable — no diagnostics to help. That's what my comment in #68 addresses.

**Comment by brianblakely** [comment]
Agreed @xdgc -- not needing Chrome installed is ideal.

As for the bug report, I grabbed a random MacBook from someone to test.  I knew nothing about its existing setup, I just installed Node and my fork of nativefier, added the Spotify Web Player, and it worked as expected.

My own machine runs Windows, and has the latest Chrome 61 running.  I've tested various scenarios on that environment, and have not been able to break it yet.

**Comment by brianblakely** [comment]
Any response to my previous comment?

**Comment by mikhoul** [comment]
@brianblakely   Next week I will try your fork since I want to have Spotify and some other apps that require DRM.

Regards :octocat:

**Comment by brianblakely** [comment]
@mikhoul Great! Afterwards, please kindly report back in as much detail as you can.

**Comment by jiahaog** [comment]
@xdgc @brianblakely Ah yes, you're right about the incompatibility issue between the chrome version drift and Electron Chrome version. 

Could we then have some form of pop up to inform the user when the plugin has completed the download?

**Comment by Mach7Seven** [comment]
Has this been fixed? 

I see the code in the main.js file in the source, pulling widevine plugin from Chrome 6103163100

```
const WIDEVINE_PATH = '/Applications/Google Chrome.app/Contents/Versions/61.0.3163.100/Google Chrome Framework.framework/Libraries/WidevineCdm/_platform_specific/mac_x64/widevinecdmadapter.plugin';
const WIDEVINECDM_VERSION = '1.4.8.1008';

```

But it is not working. I manage to find that specific version of Chrome, and put it in /Applications. The widevine plugin inside is 1.4.8.1008 (ref. in the main.js source file)

Not working here. I have Nativefier v. 7.5.4

Has this been implemented?

**Comment by iceequal** [comment]
@brianblakely Probably a silly question but how did you install your fork of nativefier to try it out? On a Mac I've tried:
`npm install git+https://github.com/brianblakely/nativefier.git -g` and
`npm install brianblakely/nativefier -g` etc 

but I'm receiving `ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/nativefier/lib/cli.js'`

**Comment by ryanmusante** [comment]
Is nativefier widevine compatible now? What steps are necessary to implement?

**Comment by ronjouch** [comment]
> *"Is nativefier widevine compatible now? What steps are necessary to implement?"*

@ryanmusante there are unaddressed comments above that prevent merging, and I haven't paid attention to it as I have no subscription to DRM-using webapps letting me test it.

@brianblakely can you sum up remaining TODOs? Should I leave this open?

**Comment by ronjouch** [comment]
Closing. @brianblakely @ryanmusante (or anyone else able to test&finish this patch), feel free to chime in anytime with answers to the remaining questions, and I'll re-open 🙂.

**Comment by AlexGrafe** [comment]
Hi everyone. Did someone solve this? I'm still unable to watch Netflix due to Netflix error code `M7701-1003`. Would be great to have this since Netflix, Amazon Video etc. should be an important use case for nativefier.

@ronjouch @jiahaog <3

**Comment by KevinRignault** [comment]
Hi everyone,
Still the same error for me too, do you have some solutions please ? :)
Thanks !

**Comment by FanderWasTaken** [comment]
> Closing. @brianblakely @ryanmusante (or anyone else able to test&finish this patch), feel free to chime in anytime with answers to the remaining questions, and I'll re-open slightly_smiling_face.

I know this has been closed for a long time, but is there anything that can be done with DRM protected content not working? I can't write any code, so most I can do is just test changes, unfortunately :(



And yeah, I can install and use Flatpak version of Spotify, but I don't want to, and I think there are other services out there that have same issue when it comes to using them with nativefier.

**Comment by wgorski** [comment]
I'm getting the same problem with Spotify. Has anyone been able to solve this?

image

**Comment by brianblakely** [comment]
This has been fixed for literally years (since the PR was first submitted), but they wanted a pop-up message or something? I'm very sorry to be frank, but this should have just been merged. Browsers don't display a pop-up to inform you that WideVine exists, I don't understand why that was ever considered a blocker.

**Pull request closed without merging**
