### PR TITLE
Fix #327 - Update dependencies, enforce Node>=4.0, and default to Electron 1.6.6

### LINKED ISSUE #327: Update dependencies (starting with Electron)
Absolutely love Nativefier @jiahaog, but the dependencies seem to be outdated, is it going to be upgraded anytime soon?
Thanks in advance.

### PR DESCRIPTION
**Pull request by ronjouch**
Do ***NOT*** merge this PR right now, it deserves some time of cross-OS testing.

### CODE REVIEW

**Comment by ronjouch** [comment]
Aaaalright, that being said: this is the fastest, laziest, YOLOest, shoot-from-the-hip-est npm mass-update ever, I didn't even read release notes for major versions of new deps. That being said, IT WORKS FOR ME \o/ under Linux, so I figured I'd do the homework later and would start by pushing this and asking feedback from interested people 😃.

So, @jiahaog @darrenhaken and (as you showed interest in https://github.com/jiahaog/nativefier/issues/327) @ambonium @maxdec @danimalweb: could you try this branch?

1. Follow [our developer documentation](https://github.com/jiahaog/nativefier/blob/development/docs/development.md).
2. Checkout the PR: `git fetch origin pull/341/head:deps && git checkout deps`
2. Then, all feedback welcome about `npm test` and, of course, re-nativefying your apps and running for a few days with them :) . Please indicate your OS/Node for all positive/negative feedback.

Thanks everyone!

**Comment by ronjouch** [comment]
@jiahaog @darrenhaken update compatibility checking homework done. I think everything is 💚 green, and adjusted a few minor knobs. If anything, the `electron-packager` changes (linked below) deserves a look, only to know about new features we might be interested in. Pushed an updated commit, ***tests welcome*** :) , and here are my deps update notes:

* ***App***
    * [electron-window-state](https://github.com/mawie81/electron-window-state/releases) 3.0.3 → 4.1.0
        * Nothing: single breaking change happened in 4.0.0, which *"drops support for electron versions < 1.0.0"*) and nativefier already ships 1.1.3.
* ***Deps***
    * [async](https://github.com/caolan/async/releases) 1.5.2 → 2.3.0
        * Usage: `async.waterfall` in `src/build/buildMain.js, src/options/optionsMain.js`, and `async.eachSeries` in `test/module/index-spec.js`.
        * Only change I see about those was in 2.0.0 for [Waterfall multiple callback defense](https://github.com/caolan/async/pull/1050), but I don't see such usage in our code.
    * [axios](https://github.com/mzabriskie/axios/blob/master/CHANGELOG.md) 0.11.1 → 0.16.1
        * Usage: `.get` in `src/infer/inferUserAgent.js` and `src/helpers/helpers.js`, not impacted by breaking changes.
    * [cheerio](https://github.com/mzabriskie/axios/blob/master/CHANGELOG.md) 0.20.0 → 0.22.0
        * Usage: `.load` in `src/infer/inferTitle.js`, not impacted.
    * [electron-packager](https://github.com/electron-userland/electron-packager/blob/master/NEWS.md) 7.0.1 → 8.6.0
        * Usage: `.packager()` in `src/build/buildMain.js`, with options passed from `src/options/optionsMain.js`.
        * 7.6.0 enforced minimum Node version, which we should too; updated our `package.json` with `">= 4.0"`.
        * 8.5.0 renamed option `version` into `electronVersion`; updated our options factory.
    * [progress](https://github.com/visionmedia/node-progress/blob/master/CHANGELOG.md) 1.1.8 → 2.0.0
        * Usage: `ProgressBar` in `src/helpers/dishonestProgress.js`, nada.
    * [tmp](https://github.com/raszi/node-tmp/compare/v0.0.28...v0.0.31) 0.0.28 → 0.0.31
        * Usage: `.setGracefulCleanup`, `.dirSync`, all clear.
    * [validator](https://github.com/chriso/validator.js/blob/master/CHANGELOG.md) 5.2.0 → 7.0.0
        * Usage: `.isURL` in `src/options/normalizeUrl.js`, nada.
* ***devDeps***
    * gulp-istanbul 0.10.3 → 1.1.1, gulp-mocha 2.2.0 → 4.3.0, gulp-sourcemaps 1.6.0 → 2.5.1
        * Eh, if something's broken, tests will fail `¯\_(ツ)_/¯`.

**Comment by jiahaog** [comment]
@ronjouch Thanks, really awesome job! Let me do some testing on my side, and go through the changes with electron packager

**Comment by ronjouch** [comment]
Status for smoke tests:

* 💚 for Arch and Ubuntu Linux on Node 7.
* 💚 for Windows10 on Node 6 LTS.
* ❓ for macOS, @darrenhaken on it.

**Comment by maxdec** [comment]
The tests pass for me on macOS (10.12.4) with Node 7.9.0
I'll try to migrate Messenger and Plex and see if I notice anything.

**Comment by jiahaog** [comment]
Works fine on my mac @ronjouch, thanks alot!

**Comment by ronjouch** [comment]
Alright let's merge this and cut a release soon!

**Pull request merged**
