### PR TITLE
Added icon-status option

### PR DESCRIPTION
**Pull request by thiagotognoli**
Added icon-status option, to change icon in tray when window title count change and return to normal icon on window focus

### CODE REVIEW

**Comment by ronjouch** [comment]
Hi @thiagotognoli and thanks for the contribution.

Is this something similar to https://github.com/jiahaog/nativefier/issues/962 ? Can you share a few screenshots?

**Comment by thiagotognoli** [comment]
Thank you @ronjouch 

Hi,

Is similar with #962 when do you say "just a bright red dot on unread messages"

Bellow prints:
When init app:
image

With app minimized and receive a e-mail:
image

When focus in app
image

To run this sample using my branch:

nativefier "https://mail.google.com/" \
    --maximize \
    --tray \
    --single-instance \
    --icon "icon.png" \
    --icon-status "icon_msg.png" \
    --counter \
    --name "Gmail" \
    --user-agent "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0" \
    --internal-urls "(.*?mail\.google\.com.*?|.*?accounts\.google\.com.*?)" \
    --electron-version 7.1.11

**Comment by ronjouch** [comment]
@thiagotognoli sorry for the delay.

That's cool, but I'm not a fan of asking users to pass a "status icon" they have to craft themselves by:

1. Extracting the site icon
2. Fire up their image editor, add a red dot (or whatever they please)
3. Save the icon somewhere
4. Pass it as `--icon-status`

Did you investigate the possibility to do the "red dot overlaying on top of current icon" programmatically? Are there enough Electron APIs / JS image manipulation libs to do that? That way a user could simply pass a flag `--counter-flag-icon-on-increase`

**Comment by bkmo** [comment]
I have tried to clone your branch in order to try this, but I always seem to get nativefier 9.0.0 without the --icon-status  option.

> To run this sample using my branch:
> 
> nativefier "https://mail.google.com/"
> --maximize
> --tray
> --single-instance
> --icon "icon.png"
> --icon-status "icon_msg.png"
> --counter
> --name "Gmail"
> --user-agent "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0"
> --internal-urls "(._?mail.google.com._?|._?accounts.google.com._?)"
> --electron-version 7.1.11

**Comment by renyhp** [comment]
I patched the app to add a `--icon-tray` option to this PR, so that I can customize the tray icon, other than the "status" icon. My patch, however, is not ready for a PR, because in absence of the `--icon-tray` option it should fall back to `--icon` (or to inferIcon), which is something I have no idea how to code.

By the way I rebased this PR (and my patch) onto the current master branch, resolving the merge conflicts. I filed a [PR](https://github.com/thiagotognoli/nativefier/pull/1) at thiagotognoli:master.

**Comment by ronjouch** [comment]
Closing for now, see https://github.com/jiahaog/nativefier/pull/967#issuecomment-643631795 . Happy to re-open when it's answered/addressed 🙂.

**Pull request closed without merging**
