### PR TITLE
Automatically create Linux launchers

### PR DESCRIPTION
**Pull request by leonidasv**
This PR should solve #204 and #345

### CODE REVIEW

**Comment by leonidasv** [comment]
I don't know exactly why the CI failed, but it looks like it was running in a Linux server but downloaded Electron for darwin-x64.

**Comment by martasd** [comment]
Is anyone still looking into this?

**Comment by zaen323** [comment]
I desperately need this.. :))

**Comment by EriKWDev** [comment]
Any updates here? This seems like an otherwise wonderful PR! ^^

**Comment by rathboma** [comment]
If we can please take a look at this, super important for Linux users, current workflow is:

1. Realize there's no desktop file
2. Google frantically about natifier and desktop files
3. Find issue #204 
4. Manually create a desktop file, including having to manually run terminal programs and such
5. Finally find this PR and be sad it's been sitting for a year :-(

Even if there was a note in the README about this it would help

**Comment by tristangodfrey** [comment]
@rathboma I'll be working on adding this as soon as I have a bit of spare time, but implementing it is fairly trivial so if you need it quickly feel free to take a stab at it! This PR can be binned I think as the project migrated to typescript recently and rebasing would be messy

**Comment by rathboma** [comment]
Ah, I was missing that context. If I get time I'll take a stab, doesn't seem too complex. Although with COVID finding time is not easy :-).

**Comment by ronjouch** [comment]
Better late than never, here's my reason for not merging this in its current state: https://github.com/jiahaog/nativefier/issues/204#issuecomment-683499262 . Comments welcome, in the issue please and not in this PR (for discussion centralization).

**Comment by ronjouch** [comment]
> Better late than never, here's my reason for not merging this in its current state: [#204 (comment)](https://github.com/jiahaog/nativefier/issues/204#issuecomment-683499262) . Comments welcome, in the issue please and not in this PR (for discussion centralization).

Will merge a PR implementing https://github.com/jiahaog/nativefier/issues/204#issuecomment-683499262 . For now, closing the current PR, to be clear it's not considered, see linked discussion.

**Pull request closed without merging**
